In [1]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr)
print(arr.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)


In [27]:
arr = np.arange(0,10).reshape(5,2)
print(arr)
arr.shape

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


(5, 2)

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
arra = np.array([[1,2,3],[3,4,5]])
print(arra.ndim)
print(arra.size)
print(arra.dtype)
print(arra.itemsize)

2
6
int64
8


In [56]:
arr2 = np.array([1,81,4,169,16,25])
arr3 = np.array([10,20,30,40,50,60])

print(arr2+arr3)

[ 51  91  44 199  29 115]


In [60]:
print(np.sqrt(arr2))
# print(np.exp(arr))
print(np.sin(arr3))

[ 1.  9.  2. 13.  4.  5.]
[-0.26237485 -0.54402111  0.74511316 -0.98803162  0.42016704  0.89399666]


In [69]:
# Statistical Methods


data = np.array([10,20,30,40,50,60])

mean = np.mean(data)
sd = np.std(data)

Normalized = (data - mean)/sd
print(Normalized)

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [73]:
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

35.0
35.0
17.07825127659933
291.6666666666667


0
